<?php

namespace phpseclib\Net;

use phpseclib\Common\Enum;

class SSH2_DISCONNECT extends Enum
{
    const DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECT = 1;
    const DISCONNECT_PROTOCOL_ERROR = 2;
    const DISCONNECT_KEY_EXCHANGE_FAILED = 3;
    const DISCONNECT_RESERVED = 4;
    const DISCONNECT_MAC_ERROR = 5;
    const DISCONNECT_COMPRESSION_ERROR = 6;
    const DISCONNECT_SERVICE_NOT_AVAILABLE = 7;
    const DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTED = 8;
    const DISCONNECT_HOST_KEY_NOT_VERIFIABLE = 9;
    const DISCONNECT_CONNECTION_LOST = 10;
    const DISCONNECT_BY_APPLICATION = 11;
    const DISCONNECT_TOO_MANY_CONNECTIONS = 12;
    const DISCONNECT_AUTH_CANCELLED_BY_USER = 13;
    const DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLE = 14;
    const DISCONNECT_ILLEGAL_USER_NAME = 15;

    //Text reasons
    const KEY_EXCHANGE_FAILED='KEY_EXCHANGE_FAILED';
    const BY_APPLICATION='BY_APPLICATION';
    const AUTH_CANCELLED_BY_USER='AUTH_CANCELLED_BY_USER';
    const HOST_KEY_NOT_VERIFIABLE='HOST_KEY_NOT_VERIFIABLE';

}
