<?php

namespace phpseclib\Net;

use phpseclib\Common\Enum;

class SSH_DISCONNECT extends Enum
{
    const HOST_NOT_ALLOWED_TO_CONNECT = 1;
    const PROTOCOL_ERROR = 2;
    const KEY_EXCHANGE_FAILED = 3;
    const RESERVED = 4;
    const MAC_ERROR = 5;
    const COMPRESSION_ERROR = 6;
    const SERVICE_NOT_AVAILABLE = 7;
    const PROTOCOL_VERSION_NOT_SUPPORTED = 8;
    const HOST_KEY_NOT_VERIFIABLE = 9;
    const CONNECTION_LOST = 10;
    const BY_APPLICATION = 11;
    const TOO_MANY_CONNECTIONS = 12;
    const AUTH_CANCELLED_BY_USER = 13;
    const NO_MORE_AUTH_METHODS_AVAILABLE = 14;
    const ILLEGAL_USER_NAME = 15;

    //Text reasons
    const KEY_EXCHANGE_FAILED_TXT='KEY_EXCHANGE_FAILED';
    const BY_APPLICATION_TXT='BY_APPLICATION';
    const AUTH_CANCELLED_BY_USER_TXT='AUTH_CANCELLED_BY_USER';
    const HOST_KEY_NOT_VERIFIABLE_TXT='HOST_KEY_NOT_VERIFIABLE';

}
